/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */


#include <pbs_config.h>   /* the master config generated by configure */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "pbs_ifl.h"
#include "attribute.h"
#include "pbs_error.h"
#include "libpbs.h"


/**
 * @brief	Generic attribute setter function, accepts all values as string regardless of the type
 *
 * @param[in]	pattr	-	pointer to attribute being set
 * @param[in]	pdef 	-	attribute definition
 * @param[in]	pobj	-	pointer to attribute definition
 * @param[in]	value	-	value to be set
 *
 * @return	void
 *
 * @par MT-Safe: No
 * @par Side Effects: None
 *
 */
void
set_attr_generic(attribute *pattr, attribute_def *pdef, char *value, enum batch_op op)
{
	int rc;
	attribute tempat;

	if (pattr == NULL || pdef == NULL) {
		log_err(-1, __func__, "Invalid pointer to attribute or its definition");
		return;
	}

	clear_attr(&tempat, pdef);
	if ((rc = pdef->at_decode(&tempat, pdef->at_name, NULL, value)) != 0)
		log_errf(rc, __func__, "decode of %s failed", pdef->at_name);

	set_attr_with_attr(pdef, pattr, &tempat, op);

	pdef->at_free(&tempat);
}

/**
 * @brief	Set attribute using another attribute
 *
 * @param[in]	pdef 	-	attribute definition
 * @param[in]	oattr	-	pointer to attribute being set
 * @param[in]	nattr	-	pointer to attribute to set with
 * @param[in]	op		-	operation to do
 *
 * @return	void
 *
 * @par MT-Safe: No
 * @par Side Effects: None
 *
 */
void
set_attr_with_attr(attribute_def *pdef, attribute *oattr, attribute *nattr, enum batch_op op)
{
	int rc;

	if ((rc = pdef->at_set(oattr, nattr, op)) != 0)
		log_errf(rc, __func__, "set of %s failed", pdef->at_name);
}

/**
 * @brief	Attribute setter function for long type values
 *
 * @param[in]	pattr	-	pointer to attribute being set
 * @param[in]	value	-	value to be set
 *
 * @return	void
 *
 * @par MT-Safe: No
 * @par Side Effects: None
 *
 */
void
set_attr_l(attribute *pattr, long value, enum batch_op op)
{
	if (pattr == NULL) {
		log_err(-1, __func__, "Invalid pointer to attribute");
		return;
	}

	switch (op) {
		case SET:
			pattr->at_val.at_long = value;
			break;
		case INCR:
			pattr->at_val.at_long += value;
			break;
		case DECR:
			pattr->at_val.at_long -= value;
			break;
		default:
			return;
	}

	pattr->at_flags |= ATR_SET_MOD_MCACHE;
}

/**
 * @brief	Attribute setter function for char type values
 *
 * @param[in]	pattr	-	pointer to attribute being set
 * @param[in]	value	-	value to be set
 *
 * @return	void
 *
 * @par MT-Safe: No
 * @par Side Effects: None
 *
 */
void
set_attr_c(attribute *pattr, char value, enum batch_op op)
{
	if (pattr == NULL) {
		log_err(-1, __func__, "Invalid pointer to attribute");
		return;
	}

	switch (op) {
		case SET:
			pattr->at_val.at_char = value;
			break;
		case INCR:
			pattr->at_val.at_char += value;
			break;
		case DECR:
			pattr->at_val.at_char -= value;
			break;
		default:
			return;
	}

	pattr->at_flags |= ATR_SET_MOD_MCACHE;
}

char
get_attr_c(const attribute *pattr)
{
	if (pattr != NULL) {
		return  pattr->at_val.at_char;
	}
	return -1;
}

long
get_attr_l(const attribute *pattr)
{
	if (pattr != NULL) {
		return  pattr->at_val.at_long;
	}
	return -1;
}

